name: Pixelfucker
favicon: null
layout_spectrum: 0.9096216335892677
typography_spectrum: 0.25542521430179477
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4860967576969415
  lightness: 0.2838671535719186
  saturation: 0.0956596564501524
  rhythmicContrast: 0.025889172684401274
purpose: []
